name: Deploy

on:
  pull_request:
    branches:
      - master

env:
  artifactName: 'wwwroot'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run './build.cmd Publish'
      run: ./build.cmd Publish
    - uses: actions/upload-artifact@v1
      with:
        name: $artifactName
        path: artifacts/wwwroot

  deploy-test:
    environment: QA
    needs: build
    name: Deploy to QA
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${ NETLIFY_AUTH_TOKEN }
      NETLIFY_SITE_ID: ${ NETLIFY_SITE_ID }
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: $artifactName
    - name: Run './build.cmd Deploy'
      run: ./build.cmd Deploy --deploy-artifact-path ./$artifactName

  deploy-prod:
    environment: Prod
    needs: build
    name: Deploy to Prod
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${ NETLIFY_AUTH_TOKEN }
      NETLIFY_SITE_ID: ${ NETLIFY_SITE_ID }
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: $artifactName
    - name: Run './build.cmd Deploy'
      run: ./build.cmd Deploy --deploy-artifact-path ./$artifactName --prod